name: Linux Command Execution and Commit File

on:
  push:
    branches:
    - main

  workflow_dispatch:
  

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Install dependencies
      run: sudo apt-get install libegl1-mesa

    - name: Run a command
      run: |
        Xvfb :1 & export DISPLAY=:1; ./build/linux/x64/release/bundle/readme_tier_list_generator

    - name: ls
      run: ls *.png -l -h

    - name: Get git info
      run: git remote -v


    - name: Commit and Push
      run: |
        git config user.name 'Automation'
        git config user.email 'automation@example.com'
        git add .
        git commit -m "Ajout du fichier généré"
        git push
