name: Linux Command Execution and Commit File

on:
  push:
    branches:
    - main

  workflow_dispatch:
  

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Install ubunto directory 
      run: sudo apt-get install libgtk-3-0 libblkid1 liblzma5


    - name: Run a command
      run: |
         ./build/linux/x64/release/bundle/readme_tier_list_generator &


    - name: Commit and Push
      run: |
        git config user.name 'VotreNom'
        # git config --global user.email 'votreemail@example.com'
        git add .
        git commit -m "Ajout du fichier généré"
        git push
